In [1]:
# Name: Parth Jilubhai Dethaliya
# Reg No: 24-27-29
# Programme: M.Tech. Data Science
# Assignment Number: 2

In [2]:
import numpy as np
def print_var_info(var):
    print(f"values    : \n{var}")
    print(f"Shape     : {var.shape}")
    print(f"Dimension : {var.ndim}")

In [3]:
## Q1
# a 
var1 = np.arange(31) # including 0 and 30 as well, total 31 values

print_var_info(var1)

values    : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape     : (31,)
Dimension : 1


In [4]:
# b
# Since 31 values are present in var1 (5,6) or (6,5) shapes may not work so,
var2 = var1.reshape(31,1)

print_var_info(var2)

values    : 
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Shape     : (31, 1)
Dimension : 2


In [5]:
# c
# Similarly 3d shape
var3 = var2.reshape(1,31,1) # or var1.reshape() both would result in same

print_var_info(var3)

values    : 
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]
Shape     : (1, 31, 1)
Dimension : 3


In [6]:
# d

var2[1,0] = -1

print(var1)
print(var3)

[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0]
  [-1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


The values in var1 as well as var3 changes because reshapes doesn't returns copy rather it returns view (in most of the cases).

In [7]:
# e i) Sum var3 over its second dimension
print(f"Shape     : {var3.shape}")

sum_var3_ax1 = np.sum(var3, axis=1)
print("Sum over second dimension:", sum_var3_ax1) # Second dimension contains all the 31 values so it sums over it

# e ii) Sum var3 over its 3rd dimension

sum_var3_ax2 = np.sum(var3, axis=2)
print("Sum over second dimension:", sum_var3_ax2) # it will sum between columns but since we only have 31 rows and 
# single column so it will be same thing but with dimension 2 (as it has reduced that 2nd axis by summin over it)

# e iii) Sum var3 over its 1st & 3rd dimension


sum_var3_ax1_3 = np.sum(var3, axis=(0,2))
print("Sum over second dimension:", sum_var3_ax1_3) # it willfirst sum over axis 0 which is between the depth, but since 
# there exists only one depth so the output information may not change, only axis 0 will be reduces
# then it sums over axis 2, again same thing will happen as mention in "e (ii)" and the dimension will be 1 now

Shape     : (1, 31, 1)
Sum over second dimension: [[463]]
Sum over second dimension: [[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]
Sum over second dimension: [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


Conclusion regarding output shape:
if an array is of shape (a,b,c),
any_operation(axis=0) returns (b,c) (eliminates the given axis)
example: i) any_operation(axis=1) returns (a,c)
         ii) any_operation(axis=(0,1) returns (b) likewise...

In [8]:
# f i)
print("Second row")
print(var2[2,:])

# f ii)
print("\nLast column")
print(var2[:,-1]) # Only 1 column exists so the output will with full data but 1d

# f iii) Top right 2x2
# Since it's not possible with shape (31,1) so creating new variable with (5,6) shape to do this
var4 = np.arange(30).reshape(5,6)
print("\nvar4: ")
print_var_info(var4)

print("\n")
print("Top right 2x2: \n")

print(var4[:4,-4:])


Second row
[2]

Last column
[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]

var4: 
values    : 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Shape     : (5, 6)
Dimension : 2


Top right 2x2: 

[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]


In [9]:
# Q2
# a
arr = np.arange(10)
print("original array  : ", arr)
arr2 = arr + 1
print("Broadcasted + 1 : ",arr2)

original array  :  [0 1 2 3 4 5 6 7 8 9]
Broadcasted + 1 :  [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# b 10x10 matrix
column_vector = arr2.reshape(10,1) 
arr3 = column_vector + arr2 

In [11]:
arr3

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [12]:
# c

import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
print(data)

[[ 0.38235034  0.47052197  0.53214629  0.40205941  2.91523004]
 [ 2.09759357  6.7715061   1.87417993  2.23864297  1.32071546]
 [ 0.87450436  0.32739146  1.67193682  1.66378008  0.62403148]
 [ 0.24493919  0.70024222  0.58580026  0.85574078  1.92754272]
 [ 0.21456058  0.60270527  1.0972436   0.79434142  1.4114013 ]
 [ 0.48448822  0.72102741  0.87042439  0.57519546  0.86214031]
 [ 1.7380417   1.36251009  3.05740094  7.82942831  1.01136941]
 [ 1.09660995  0.82763883  3.91180426  0.89560132  1.19201264]
 [ 0.46463446  0.75688305  2.30421174  1.37665969  0.57275142]
 [ 0.17485048  1.049277    0.27547992  1.1294214   1.25206785]
 [ 0.35353941  1.10328982  0.68705863  0.4821      4.88034987]
 [ 1.27380803  0.40903791  0.30665223  2.33216675  0.61671796]
 [ 2.46778942  0.86358348  0.2519135   0.49389942  0.47557763]
 [ 0.59847432  1.56789963  0.61186137  0.46275371  3.87413232]
 [ 2.43903977  5.22751147  1.06642947  0.33476891  0.67491127]
 [ 0.06963168  1.26421882  1.1115445   0.06367931  2.01

In [13]:
std = np.std(data,axis=0)# for each column that means we have to compute between rows
mean = np.mean(data,axis=0)
print(std)
print(mean)

[2.53622086 2.69123172 1.24231533 2.4336724  1.10454843]
[1.7053151  2.00756827 1.27562354 1.80731343 1.25703347]


In [14]:
normalized = (data-mean)/std
print(normalized)

[[-5.21628371e-01 -5.71131163e-01 -5.98460980e-01 -5.77421193e-01
   1.50124388e+00]
 [ 1.54670470e-01  1.77017006e+00  4.81807135e-01  1.77234017e-01
   5.76543211e-02]
 [-3.27578227e-01 -6.24315178e-01  3.19011821e-01 -5.89780885e-02
  -5.73086685e-01]
 [-5.75807860e-01 -4.85772383e-01 -5.55272289e-01 -3.91002769e-01
   6.07043779e-01]
 [-5.87785764e-01 -5.22014878e-01 -1.43586681e-01 -4.16231870e-01
   1.39756510e-01]
 [-4.81356689e-01 -4.78049085e-01 -3.26164493e-01 -5.06279307e-01
  -3.57515479e-01]
 [ 1.29036863e-02 -2.39688828e-01  1.43423924e+00  2.47449693e+00
  -2.22411307e-01]
 [-2.40004788e-01 -4.38434724e-01  2.12199001e+00 -3.74624010e-01
  -5.88664352e-02]
 [-4.89184778e-01 -4.64725952e-01  8.27960638e-01 -1.76956331e-01
  -6.19512949e-01]
 [-6.03442956e-01 -3.56079065e-01 -8.05064218e-01 -2.78546953e-01
  -4.49561139e-03]
 [-5.32988160e-01 -3.36009139e-01 -4.73764503e-01 -5.44532382e-01
   3.28035993e+00]
 [-1.70137811e-01 -5.93977228e-01 -7.79972108e-01  2.15663095e-01

In [15]:
std = np.std(normalized,axis=0)
mean = np.mean(normalized,axis=0)
print("Standard Deviation : ",std)
print("Mean               : ",mean)
# Mean 0, Std = 1

Standard Deviation :  [1. 1. 1. 1. 1.]
Mean               :  [ 1.23234756e-16 -1.06581410e-16 -6.66133815e-18 -4.55191440e-17
  3.36397576e-16]


In [16]:
# 3 Vandermonde matrix

N = 12
def vandermonde(N):
    vec = np.arange (N) +1
    vector = np.arange(N) + 1
    v2 = np.arange(N)  # Power Vector 
    output = vector.reshape(N,1)**v2
    return output
def printMat(Mat):
    for row in Mat:
        print(" ".join(f"{elem}" for elem in row))

Vector = vandermonde(N)
printMat(Vector)

1 1 1 1 1 1 1 1 1 1 1 1
1 2 4 8 16 32 64 128 256 512 1024 2048
1 3 9 27 81 243 729 2187 6561 19683 59049 177147
1 4 16 64 256 1024 4096 16384 65536 262144 1048576 4194304
1 5 25 125 625 3125 15625 78125 390625 1953125 9765625 48828125
1 6 36 216 1296 7776 46656 279936 1679616 10077696 60466176 362797056
1 7 49 343 2401 16807 117649 823543 5764801 40353607 282475249 1977326743
1 8 64 512 4096 32768 262144 2097152 16777216 134217728 1073741824 0
1 9 81 729 6561 59049 531441 4782969 43046721 387420489 -808182895 1316288537
1 10 100 1000 10000 100000 1000000 10000000 100000000 1000000000 1410065408 1215752192
1 11 121 1331 14641 161051 1771561 19487171 214358881 -1937019605 167620825 1843829075
1 12 144 1728 20736 248832 2985984 35831808 429981696 864813056 1787822080 -20971520


In [17]:
# b

x = np.ones(12)

b = np.dot(Vector,x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [18]:
# c naive solution

Vector_inv = np.linalg.inv(Vector)
Sol = np.dot(Vector_inv,b)
print(Sol)
# The result is almost ones(12) with slight variation maybe due to floating points instability while inversing Vector

[1.00158882 0.99722672 1.00127029 0.99991608 1.00000095 0.99999905
 1.00000018 0.99999999 1.         1.         1.         1.        ]


In [19]:
# d solve using numpy

Sol_inbuilt = np.linalg.solve(Vector,b)

print(Sol_inbuilt)

[1.0000114  0.99997033 1.00002961 0.99998507 1.00000423 0.9999993
 1.00000007 1.         1.         1.         1.         1.        ]


In [20]:
# The solution using .solve() seems more accurate but let's verify that using some statistics 

Diff_solve = x - Sol
Diff_solve_inbuilt = x - Sol_inbuilt
print(np.std(Diff_solve) , np.std(Diff_solve_inbuilt) )
# clearly the inbuilt function method's solution is more closer to ones(12)

0.0009931496457600455 1.3316958977450673e-05


In [21]:
#https://github.com/PARTH1D/Parth_24-27-29/blob/main/Assn2_Parth_Dethaliya_24-27-29.ipynb